"use client";
import "../styles/globals.css";
import { Suspense, useEffect, useState } from "react";
import Cookies from "js-cookie";
import { useRouter, useSearchParams } from "next/navigation";
import axios from "axios";
// export const metadata = {
//   title: " masjed ",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const router = useRouter();
  const params = useSearchParams();

  useEffect(() => {
    const fetching = async () => {
      // بررسی اگر توکن از URL آمده است
      const tokenFromParams = params.get("jwt");
      if (tokenFromParams) {
        Cookies.set("token", tokenFromParams);
        window.history.replaceState(null, "", "/");
        return;
      }

      // بررسی اگر توکن در کوکی ذخیره شده
      const accessToken = Cookies.get("token");
      
      if (!accessToken) {
        // اگر توکن وجود نداشت، به صفحه لاگین هدایت می‌کنیم
        try {
          const url = await axios.get("/api/url");
          if (url.data) {
            router.push(url.data.verify_url);
          }
        } catch (error) {
          console.log(error);
        }
      } else {
        // اگر توکن وجود داشت، اعتبار آن را با API پروفایل بررسی می‌کنیم
        try {
          await axios.get(`/api/profile`, {
            headers: {
              Accept: "application/json",
              Authorization: `bearer ${accessToken}`,
            },
          });
          // اگر خطایی نبود، یعنی توکن معتبر است
        } catch (error) {
          console.log("توکن نامعتبر است:", error);
          // در صورت خطا، توکن را حذف می‌کنیم و کاربر را به صفحه لاگین هدایت می‌کنیم
          Cookies.remove("token");
          try {
            const url = await axios.get("/api/url");
            if (url.data) {
              router.push(url.data.verify_url);
            }
          } catch (urlError) {
            console.log(urlError);
          }
        }
      }
    };
    
    fetching();
  }, []);

  return (
    <html dir="rtl" lang="fa">
      <body className="relative">
        <Suspense>{children}</Suspense>
      </body>
    </html>
  );
}