"use client";
import "../styles/globals.css";
import { Suspense } from "react";
// export const metadata = {
//   title: " masjed ",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html dir="rtl" lang="fa">
      <body className="relative">
        <Suspense>{children}</Suspense>
      </body>
    </html>
  );
}
